"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { cats, isScreen, items, money, tables, type Cat, type Item, type Screen } from "./data";
import { FoodImage, Footer, Line, Panel, Qty, Shell, Top } from "./ui";

export default function StableCustomerApp(){
 const [screen,setScreen]=useState<Screen>("menu");
 const [cat,setCat]=useState<Cat>("All");
 const [search,setSearch]=useState("");
 const [cart,setCart]=useState<Record<number,number>>({});
 const [table,setTable]=useState(3);
 const [selected,setSelected]=useState(items[0]);
 const [note,setNote]=useState("");
 const [called,setCalled]=useState(false);
 const depth=useRef(0);
 useEffect(()=>{history.replaceState({cafeScreen:"menu"},"",location.pathname);const pop=(e:PopStateEvent)=>{depth.current=Math.max(0,depth.current-1);setScreen(isScreen(e.state?.cafeScreen)?e.state.cafeScreen:"menu");scrollTo(0,0)};addEventListener("popstate",pop);return()=>removeEventListener("popstate",pop)},[]);
 const list=useMemo(()=>{const q=search.toLowerCase().trim();return items.filter(i=>(cat==="All"||i.cat===cat)&&(!q||i.name.toLowerCase().includes(q)||i.desc.toLowerCase().includes(q)))},[cat,search]);
 const cartItems=items.map(i=>({...i,qty:cart[i.id]||0})).filter(i=>i.qty>0);
 const count=cartItems.reduce((s,i)=>s+i.qty,0);
 const total=cartItems.reduce((s,i)=>s+i.price*i.qty,0);
 function go(next:Screen){setScreen(next);depth.current+=1;history.pushState({cafeScreen:next},"",location.pathname);scrollTo({top:0,behavior:"smooth"})}
 function back(){depth.current>0?history.back():setScreen("menu")}
 function add(id:number){setCart(c=>({...c,[id]:(c[id]||0)+1}))}
 function remove(id:number){setCart(c=>{const n={...c};n[id]=(n[id]||0)-1;if(n[id]<=0)delete n[id];return n})}
 function open(item:Item){setSelected(item);go("detail")}
 function callWaiter(){setCalled(true);setTimeout(()=>setCalled(false),2500)}
 function placeOrder(){if(!count)return;setCart({});setNote("");go("done")}
 if(screen==="detail")return <Detail item={selected} qty={cart[selected.id]||0} total={total} back={back} go={go} add={add} remove={remove}/>;
 if(screen==="cart")return <Cart cartItems={cartItems} total={total} table={table} note={note} setNote={setNote} back={back} go={go} add={add} remove={remove} open={open} placeOrder={placeOrder}/>;
 if(screen==="tables")return <Tables table={table} setTable={setTable} back={back} go={go}/>;
 if(screen==="allergens")return <Allergens back={back} go={go} hasCart={count>0} open={open}/>;
 if(screen==="done")return <Done table={table} go={go}/>;
 return <Shell><header className="bg-slate-900 px-3 pb-5 pt-4 text-white"><p className="text-xs font-black uppercase tracking-[0.18em] text-orange-300">The Corner Cafe</p><p className="mt-2 text-sm font-bold text-white/80">Table {table} confirmed from QR</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={callWaiter} className={called?"small-on":"small"}>{called?"Called":"Waiter"}</button><button onClick={()=>go("allergens")} className="small">Allergen info</button></div><input value={search} onChange={e=>setSearch(e.target.value)} className="mt-5 min-h-[52px] w-full rounded-2xl px-4 text-sm font-bold text-slate-900 outline-none" placeholder="Search food, coffee, cake"/></header><main className="px-3 pb-32 pt-4"><div className="flex gap-2 overflow-x-auto pb-3">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={cat===c?"cat-on":"cat"}>{c}</button>)}</div><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-orange-600">Order at your pace</p><h1 className="text-2xl font-black">Menu</h1></div><button onClick={()=>go("allergens")} className="text-sm font-black text-orange-600">Allergens</button></div><div className="grid grid-cols-1 gap-3 min-[380px]:grid-cols-2">{list.map(item=><article key={item.id} className="overflow-hidden rounded-3xl bg-white ring-1 ring-slate-200"><button onClick={()=>open(item)} className={`block w-full rounded-t-3xl bg-gradient-to-br ${item.imageClass}`}><FoodImage tone={item.imageClass}/></button><div className="p-3"><button onClick={()=>open(item)} className="w-full text-left"><h2 className="font-black">{item.name}</h2><p className="text-xs font-bold text-slate-500">{item.desc}</p></button><div className="mt-3 flex items-center justify-between"><span className="font-black">{money(item.price)}</span>{cart[item.id]?<Qty qty={cart[item.id]} minus={()=>remove(item.id)} plus={()=>add(item.id)} small/>:<button onClick={()=>add(item.id)} className="add">+</button>}</div></div></article>)}</div></main><Footer><button onClick={()=>go("cart")} className="flex min-h-16 w-full items-center justify-between rounded-2xl bg-slate-900 px-4 text-left text-white"><span><b>{count?`${count} items in basket`:`Table ${table}`}</b><span className="block text-xs text-white/65">{count?"Ready for checkout":"Add items from the menu"}</span></span><span className="rounded-xl bg-orange-500 px-3 py-3 font-black">{count?money(total):"Basket"}</span></button></Footer></Shell>
}

function Detail({item,qty,total,back,go,add,remove}:{item:Item;qty:number;total:number;back:()=>void;go:(s:Screen)=>void;add:(id:number)=>void;remove:(id:number)=>void}){return <Shell><Top title={item.name} back={back} right="Allergens" onRight={()=>go("allergens")}/><main className="px-3 pb-28 pt-4"><FoodImage tone={item.imageClass} large/><p className="mt-5 text-xs font-black uppercase tracking-[0.18em] text-orange-600">{item.cat}</p><h1 className="mt-1 text-3xl font-black">{item.name}</h1><p className="mt-2 text-sm font-bold text-slate-500">{item.desc}</p><Panel><p className="font-black">Allergens</p><p className="mt-2 text-sm text-slate-600">{item.allergens.join(", ")}</p></Panel></main><Footer>{qty?<Qty qty={qty} minus={()=>remove(item.id)} plus={()=>add(item.id)}/>:<button className="primary" onClick={()=>add(item.id)}>Add to basket · {money(item.price)}</button>}</Footer></Shell>}
function Cart({cartItems,total,table,note,setNote,back,go,add,remove,open,placeOrder}:any){return <Shell><Top title="Basket" back={back} right="Allergens" onRight={()=>go("allergens")}/><main className="space-y-3 px-3 pb-40 pt-4"><button onClick={()=>go("tables")} className="secondary flex items-center justify-between"><span>Table {table}</span><span className="text-orange-600">Change</span></button>{cartItems.length?cartItems.map((item:any)=><article key={item.id} className="rounded-3xl bg-white p-3 ring-1 ring-slate-200"><button onClick={()=>open(item)} className="text-left font-black">{item.name}</button><p className="text-sm font-bold text-slate-500">{money(item.price)}</p><Qty qty={item.qty} minus={()=>remove(item.id)} plus={()=>add(item.id)} small/></article>):<Panel><p className="font-black">Basket is empty</p></Panel>}<textarea value={note} onChange={e=>setNote(e.target.value)} className="min-h-24 w-full rounded-3xl border border-slate-200 bg-white p-4 text-sm font-bold outline-none" placeholder="Order note"/><Panel><Line label="Total" value={money(total)}/></Panel></main><Footer><button disabled={!cartItems.length} onClick={placeOrder} className="primary disabled:bg-slate-300">Place order · {money(total)}</button></Footer></Shell>}
function Tables({table,setTable,back,go}:any){return <Shell><Top title="Change table" back={back} right="Menu" onRight={()=>go("menu")}/><main className="px-3 pb-28 pt-4"><Panel><h1 className="text-2xl font-black">Select your table</h1><div className="mt-5 grid grid-cols-4 gap-3">{tables.map(id=><button key={id} onClick={()=>setTable(id)} className={table===id?"table-on":"table"}>{id}</button>)}</div><button onClick={back} className="primary mt-5">Use table {table}</button></Panel></main></Shell>}
function Allergens({back,go,hasCart,open}:any){return <Shell><Top title="Allergens" back={back} right={hasCart?"Basket":"Menu"} onRight={()=>go(hasCart?"cart":"menu")}/><main className="space-y-3 px-3 pb-28 pt-4"><div className="rounded-3xl bg-slate-900 p-5 text-white"><h1 className="text-2xl font-black">Allergen information</h1><p className="mt-2 text-sm text-white/75">Speak to staff if you have a serious allergy.</p></div>{items.map(item=><article key={item.id} className="rounded-3xl bg-white p-4 ring-1 ring-slate-200"><button onClick={()=>open(item)} className="font-black">{item.name}</button><p className="mt-2 text-sm font-bold text-slate-500">{item.allergens.join(", ")}</p></article>)}</main></Shell>}
function Done({table,go}:any){return <Shell><main className="flex min-h-[100svh] flex-col justify-center px-6 text-center"><div className="mx-auto grid h-24 w-24 place-items-center rounded-full bg-slate-900 text-3xl font-black text-white">OK</div><h1 className="mt-6 text-3xl font-black">Order sent</h1><p className="mt-3 text-sm font-bold text-slate-500">Your order has been sent to the kitchen for table {table}.</p><button onClick={()=>go("menu")} className="primary mt-6">Order more</button></main></Shell>}
